# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

# 1) Proxy all /api/* requests to FastAPI backend
[[redirects]]
  from    = "/api/*"
  to      = "http://51.44.18.63:8080/:splat"
  status  = 200
  force   = true

# 2) General rule for SPA fallback (React/Vue/...)
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
