[build]
  command = "npm run build"
  publish = "dist"

# 1) فهرس الـ SPA
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# 2) بُروكسي لكل ما يبدأ بـ /api/  
[[redirects]]
  from   = "/api/*"
  to     = "http://51.44.18.63:8080/:splat"
  status = 200
  force  = true

