[build]
  command = "npm run build"
  publish = "dist"

# 1) Redirect when the user directly visits /chat → we add a trailing slash so the proxy works correctly
#[[redirects]]
#  from    = "/chat"
#  to      = "http://51.44.18.63:8080/"
#  status  = 301
#  force   = true

# 2) Proxy all resources under /chat/ (HTML + JS + CSS + API + WebSockets)
#[[redirects]]
#  from    = "/chat/*"
#  to      = "http://51.44.18.63:8080/:splat"
#  status  = 200
#  force   = true

# 3) General rule for SPA applications (React/Vue/...):
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
