[build]
  command = "npm run build"
  publish = "dist"


# 1) Redirect when the user directly visits /chat → we add a trailing slash so the proxy works correctly
[[redirects]]
  from    = "/chat"
  to      = "https://data-dynamos.duckdns.org/"
  status  = 301
  force   = true

# 2) Proxy all resources under /chat/ (HTML + JS + CSS + API + WebSockets)
[[redirects]]
  from    = "/chat/*"
  to      = "https://data-dynamos.duckdns.org/:splat"
  status  = 200
  force   = true

# 3) General rule for SPA applications (React/Vue/...):
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
