[build]
  command = "npm run build"
  publish = "dist"

# Handle direct API requests - proxy to your backend
[[redirects]]
  from = "/api/*"
  to = "http://51.44.18.63:8080/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200