[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200


[[redirects]]
  from = "/chat/*"
  to   = "http://51.44.18.63:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/chat"
  to   = "http://51.44.18.63:8080/"
  status = 200
  force = true

